apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: istio-system
spec:
  secretName: grafana-tls-secret
  issuerRef:
    name: letsencrypt-prod-istio
    kind: ClusterIssuer
  commonName: grafana.srrain.store
  dnsNames:
  - grafana.srrain.store