apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: istio-system
spec:
  secretName: argocd-tls-secret
  issuerRef:
    name: letsencrypt-prod-istio
    kind: ClusterIssuer
  commonName: argocd.srrain.store
  dnsNames:
  - argocd.srrain.store