apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
spec:
  hosts:
  - "grafana.srrain.store"
  gateways:
  - grafana-gateway
  http:
  - match:
      - uri:
          prefix: /
    route:
      - destination:
          host: kube-prometheus-stack-grafana.monitoring.svc.cluster.local
          port:
            number: 80
