apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "app1.fullname" . }}
spec:
  minAvailable: 1  
  selector:
    matchLabels:
      {{- include "app1.selectorLabels" . | nindent 6 }}