apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "testapp.fullname" . }}
spec:
  minAvailable: 1  
  selector:
    matchLabels:
      {{- include "testapp.selectorLabels" . | nindent 6 }}