name: msa_project
services:
  app1:
    build:
      context: ./app1
    ports:
      - "5001:5001"

  app2:
    build:
      context: ./app2
    ports:
      - "5002:5002"

  app3:
    build:
      context: ./app3
    ports:
      - "5003:5003"

networks:
  default:
    name: msa_network
