{{- if .Values.cert.create -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "frontend.fullname" . }}-tls
  namespace: istio-system
spec:
  secretName: {{ .Values.cert.secretName }}
  issuerRef:
    name: {{ .Values.cert.issuerRef.name }}
    kind: {{ .Values.cert.issuerRef.kind }}
  commonName: {{ .Values.cert.commonName }}
  dnsNames:
    {{- range .Values.cert.dnsNames }}
    - {{ . | quote }}
    {{- end }}
{{- end }}
