apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "frontend.fullname" . }}
spec:
  minAvailable: 1  
  selector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 6 }}