apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{},"labels":{"argocd.argoproj.io/instance":"application"},"name":"app2","namespace":"argocd"},"spec":{"destination":{"namespace":"web","server":"https://kubernetes.default.svc"},"project":"default","source":{"helm":{"valueFiles":["values.yaml"]},"path":"Helm_Charts/AppOfApp/templates/app2","repoURL":"https://github.com/sRrAiN98/Simple_Flask.git","targetRevision":"main"},"syncPolicy":{"automated":{},"syncOptions":["CreateNamespace=true"]}}}
  creationTimestamp: "2024-10-13T13:24:00Z"
  generation: 14308
  labels:
    argocd.argoproj.io/instance: application
  name: app2
  namespace: argocd
  resourceVersion: "7359020"
  uid: af498c0a-968c-450f-8eee-97ce6a27f7a7
spec:
  destination:
    namespace: web
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: Helm_Charts/AppOfApp/templates/app2
    repoURL: https://github.com/sRrAiN98/Simple_Flask.git
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
