apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2024-10-12T15:14:45Z"
  generation: 13664
  name: cert-manager
  namespace: argocd
  resourceVersion: "7359028"
  uid: be93ee17-1554-4103-8b05-6ddb164e18fb
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: cert-manager
    helm:
      valueFiles:
      - values.yaml
      values: 'installCRDs: true'
    repoURL: https://charts.jetstack.io
    targetRevision: v1.16.1
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
