apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2024-10-12T15:10:56Z"
  generation: 88
  name: gateway
  namespace: argocd
  resourceVersion: "22702"
  uid: e392d9a9-2032-4899-ac51-37e7b95508f4
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gateway
    helm:
      valueFiles:
      - values.yaml
      values: |-
        defaults:
          service:
            type: LoadBalancer
            # type: NodePort
            externalTrafficPolicy: "Local"
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.23.2
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
