apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2024-10-14T01:20:56Z"
  generation: 12969
  name: hostpath-provisioner
  namespace: argocd
  resourceVersion: "7359049"
  uid: 70e333c9-2381-47f0-9235-3bad55521662
spec:
  destination:
    namespace: utils
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: hostpath-provisioner
    helm:
      valueFiles:
      - values.yaml
    repoURL: https://charts.rimusz.net
    targetRevision: 0.2.13
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
