apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2024-10-13T13:55:23Z"
  generation: 13214
  name: istio-ingressgateway
  namespace: argocd
  resourceVersion: "7358947"
  uid: 72a4799d-9982-423d-82fa-3e37ecae3b71
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gateway
    helm:
      valueFiles:
      - values.yaml
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.23.2
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
