apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2024-10-12T15:06:24Z"
  generation: 14406
  name: istiod
  namespace: argocd
  resourceVersion: "7359117"
  uid: 62c6b6a0-6749-4c0d-a933-8de2bbfd1a49
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: istiod
    helm:
      valueFiles:
      - values.yaml
      values: |-
        defaults:
          meshConfig:
            accessLogFile: "/dev/stdout"
            # Set accessLogEncoding to JSON or TEXT to configure sidecar access log
            accessLogEncoding: 'TEXT'
          pilot:
            resources:
              requests:
                cpu: 300m
                memory: 300Mi
        global:
          proxy:
            init:
              resources:
                requests:
                  cpu: 10m
                  memory: 128Mi
                limits:
                  cpu: 2000m
                  memory: 1024Mi
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.23.2
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
