apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2024-10-12T15:39:28Z"
  generation: 13605
  name: metallb
  namespace: argocd
  resourceVersion: "7359313"
  uid: b0fe917f-7a66-4955-be9c-a13dfac43d1c
spec:
  destination:
    namespace: metallb
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: metallb
    helm:
      valueFiles:
      - values.yaml
      values: |-
        configInline: |
          address-pools:
            - name: nginx-ip-range
              protocol: layer2
              addresses:
                - 192.168.31.101-192.168.31.110
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 6.3.13
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
