apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2024-10-15T07:25:28Z"
  generation: 12376
  name: opentelemetry-operator
  namespace: argocd
  resourceVersion: "7359027"
  uid: e72c23d2-8ca4-4a0c-9df5-129cbd42aa06
spec:
  destination:
    namespace: tracing
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: opentelemetry-operator
    helm:
      valueFiles:
      - values.yaml
      values: |-
        manager:
          collectorImage:
            repository: otel/opentelemetry-collector-k8s
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.71.0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
