apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2024-10-12T15:25:03Z"
  generation: 14801
  name: frontend
  namespace: argocd
  resourceVersion: "7359114"
  uid: 5e2acff3-10e8-46b3-97bb-aeec6484437d
spec:
  destination:
    namespace: web
    server: https://kubernetes.default.svc
  project: default
  source:
    path: Helm_Charts/front
    repoURL: https://github.com/sRrAiN98/Simple_Flask.git
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
  - deployStartedAt: "2024-10-12T15:25:55Z"
    deployedAt: "2024-10-12T15:26:10Z"
    id: 0
    initiatedBy:
      username: admin
    revision: f866bc9934a834a645c39117dd4da34bbb1f3e17
    source:
      path: Helm_Charts/front
      repoURL: https://github.com/sRrAiN98/Simple_Flask.git
      targetRevision: main
  - deployStartedAt: "2024-10-13T13:21:47Z"
    deployedAt: "2024-10-13T13:21:48Z"
    id: 1
    initiatedBy:
      username: admin
    revision: a6724813bedc36593ba331059ce22c4587d0929f
    source:
      path: Helm_Charts/front
      repoURL: https://github.com/sRrAiN98/Simple_Flask.git
      targetRevision: main
  - deployStartedAt: "2024-10-13T13:32:47Z"
    deployedAt: "2024-10-13T13:32:50Z"
    id: 2
    initiatedBy:
      automated: true
    revision: 78865fab891b9034b366b150abd61601ada1c487
    source:
      path: Helm_Charts/front
      repoURL: https://github.com/sRrAiN98/Simple_Flask.git
      targetRevision: main
  - deployStartedAt: "2024-10-13T13:50:46Z"
    deployedAt: "2024-10-13T13:50:51Z"
    id: 3
    initiatedBy:
      automated: true
    revision: 112d8016d82e5a036942a339ed4750b8f7868249
    source:
      path: Helm_Charts/front
      repoURL: https://github.com/sRrAiN98/Simple_Flask.git
      targetRevision: main
  operationState:
    finishedAt: "2024-10-14T14:14:36Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        resources:
        - group: cert-manager.io
          kind: Certificate
          name: frontend-tls
          namespace: istio-system
        revision: 112d8016d82e5a036942a339ed4750b8f7868249
        syncOptions:
        - CreateNamespace=true
        syncStrategy:
          hook: {}
    phase: Succeeded
    startedAt: "2024-10-14T14:14:34Z"
    syncResult:
      resources:
      - group: cert-manager.io
        hookPhase: Running
        kind: Certificate
        message: certificate.cert-manager.io/frontend-tls created
        name: frontend-tls
        namespace: istio-system
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 112d8016d82e5a036942a339ed4750b8f7868249
      source:
        path: Helm_Charts/front
        repoURL: https://github.com/sRrAiN98/Simple_Flask.git
        targetRevision: main
  reconciledAt: "2024-11-12T14:07:06Z"
  resources:
  - health:
      status: Healthy
    kind: Service
    name: frontend
    namespace: web
    status: Synced
    version: v1
  - kind: ServiceAccount
    name: frontend
    namespace: web
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: frontend
    namespace: web
    status: Synced
    version: v1
  - group: autoscaling
    health:
      message: recommended size matches current size
      status: Healthy
    kind: HorizontalPodAutoscaler
    name: frontend
    namespace: web
    status: Synced
    version: v2
  - group: cert-manager.io
    health:
      message: Certificate is up to date and has not expired
      status: Healthy
    kind: Certificate
    name: frontend-tls
    namespace: istio-system
    status: Synced
    version: v1
  - group: networking.istio.io
    kind: Gateway
    name: frontend
    namespace: web
    status: Synced
    version: v1
  - group: networking.istio.io
    kind: VirtualService
    name: frontend
    namespace: web
    status: Synced
    version: v1
  - group: networking.k8s.io
    health:
      status: Healthy
    kind: Ingress
    name: frontend
    namespace: web
    status: Synced
    version: v1
  - group: policy
    kind: PodDisruptionBudget
    name: frontend
    namespace: web
    status: Synced
    version: v1
  sourceType: Helm
  summary:
    externalURLs:
    - http://todo.srrain.store/
    images:
    - choi32739/todolist:frontend
  sync:
    comparedTo:
      destination:
        namespace: web
        server: https://kubernetes.default.svc
      source:
        path: Helm_Charts/front
        repoURL: https://github.com/sRrAiN98/Simple_Flask.git
        targetRevision: main
    revision: ded365d32b77cb6d30d37395019c90afe9fca652
    status: Synced
