apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2024-10-12T15:06:24Z"
  generation: 14406
  name: istiod
  namespace: argocd
  resourceVersion: "7359117"
  uid: 62c6b6a0-6749-4c0d-a933-8de2bbfd1a49
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: istiod
    helm:
      valueFiles:
      - values.yaml
      values: |-
        defaults:
          meshConfig:
            accessLogFile: "/dev/stdout"
            # Set accessLogEncoding to JSON or TEXT to configure sidecar access log
            accessLogEncoding: 'TEXT'
          pilot:
            resources:
              requests:
                cpu: 300m
                memory: 300Mi
        global:
          proxy:
            init:
              resources:
                requests:
                  cpu: 10m
                  memory: 128Mi
                limits:
                  cpu: 2000m
                  memory: 1024Mi
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.23.2
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
  - deployStartedAt: "2024-10-12T15:06:25Z"
    deployedAt: "2024-10-12T15:06:44Z"
    id: 0
    initiatedBy:
      automated: true
    revision: 1.23.2
    source:
      chart: istiod
      helm:
        valueFiles:
        - values.yaml
        values: |-
          defaults:
            pilot:
              resources:
                requests:
                  cpu: 300m
                  memory: 2048Mi
          global:
            proxy:
              init:
                resources:
                  requests:
                    cpu: 10m
                    memory: 128Mi
                  limits:
                    cpu: 2000m
                    memory: 1024Mi
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.23.2
  - deployStartedAt: "2024-10-14T14:37:05Z"
    deployedAt: "2024-10-14T14:37:08Z"
    id: 1
    initiatedBy:
      automated: true
    revision: 1.23.2
    source:
      chart: istiod
      helm:
        valueFiles:
        - values.yaml
        values: |-
          defaults:
            meshConfig:
              accessLogFile: "/dev/stdout"
              # Set accessLogEncoding to JSON or TEXT to configure sidecar access log
              accessLogEncoding: 'TEXT'
            pilot:
              resources:
                requests:
                  cpu: 300m
                  memory: 2048Mi
          global:
            proxy:
              init:
                resources:
                  requests:
                    cpu: 10m
                    memory: 128Mi
                  limits:
                    cpu: 2000m
                    memory: 1024Mi
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.23.2
  - deployStartedAt: "2024-10-15T10:30:06Z"
    deployedAt: "2024-10-15T10:30:10Z"
    id: 2
    initiatedBy:
      automated: true
    revision: 1.23.2
    source:
      chart: istiod
      helm:
        valueFiles:
        - values.yaml
        values: |-
          defaults:
            meshConfig:
              accessLogFile: "/dev/stdout"
              # Set accessLogEncoding to JSON or TEXT to configure sidecar access log
              accessLogEncoding: 'TEXT'
            pilot:
              resources:
                requests:
                  cpu: 300m
                  memory: 300Mi
          global:
            proxy:
              init:
                resources:
                  requests:
                    cpu: 10m
                    memory: 128Mi
                  limits:
                    cpu: 2000m
                    memory: 1024Mi
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.23.2
  operationState:
    finishedAt: "2024-10-15T10:30:11Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        revision: 1.23.2
        syncOptions:
        - CreateNamespace=true
    phase: Succeeded
    startedAt: "2024-10-15T10:30:06Z"
    syncResult:
      resources:
      - group: policy
        hookPhase: Running
        kind: PodDisruptionBudget
        message: poddisruptionbudget.policy/istiod configured
        name: istiod
        namespace: istio-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ServiceAccount
        message: serviceaccount/istiod unchanged
        name: istiod
        namespace: istio-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ConfigMap
        message: configmap/istio unchanged
        name: istio
        namespace: istio-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ConfigMap
        message: configmap/istio-sidecar-injector unchanged
        name: istio-sidecar-injector
        namespace: istio-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: ClusterRole
        message: clusterrole.rbac.authorization.k8s.io/istio-reader-clusterrole-istio-system
          reconciled. clusterrole.rbac.authorization.k8s.io/istio-reader-clusterrole-istio-system
          unchanged
        name: istio-reader-clusterrole-istio-system
        namespace: istio-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: ClusterRole
        message: clusterrole.rbac.authorization.k8s.io/istiod-gateway-controller-istio-system
          reconciled. clusterrole.rbac.authorization.k8s.io/istiod-gateway-controller-istio-system
          unchanged
        name: istiod-gateway-controller-istio-system
        namespace: istio-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: ClusterRole
        message: clusterrole.rbac.authorization.k8s.io/istiod-clusterrole-istio-system
          reconciled. clusterrole.rbac.authorization.k8s.io/istiod-clusterrole-istio-system
          unchanged
        name: istiod-clusterrole-istio-system
        namespace: istio-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: ClusterRoleBinding
        message: clusterrolebinding.rbac.authorization.k8s.io/istio-reader-clusterrole-istio-system
          reconciled. clusterrolebinding.rbac.authorization.k8s.io/istio-reader-clusterrole-istio-system
          unchanged
        name: istio-reader-clusterrole-istio-system
        namespace: istio-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: ClusterRoleBinding
        message: clusterrolebinding.rbac.authorization.k8s.io/istiod-gateway-controller-istio-system
          reconciled. clusterrolebinding.rbac.authorization.k8s.io/istiod-gateway-controller-istio-system
          unchanged
        name: istiod-gateway-controller-istio-system
        namespace: istio-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: ClusterRoleBinding
        message: clusterrolebinding.rbac.authorization.k8s.io/istiod-clusterrole-istio-system
          reconciled. clusterrolebinding.rbac.authorization.k8s.io/istiod-clusterrole-istio-system
          unchanged
        name: istiod-clusterrole-istio-system
        namespace: istio-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: Role
        message: role.rbac.authorization.k8s.io/istiod reconciled. role.rbac.authorization.k8s.io/istiod
          unchanged
        name: istiod
        namespace: istio-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: RoleBinding
        message: rolebinding.rbac.authorization.k8s.io/istiod reconciled. rolebinding.rbac.authorization.k8s.io/istiod
          unchanged
        name: istiod
        namespace: istio-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/istiod unchanged
        name: istiod
        namespace: istio-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/istiod configured
        name: istiod
        namespace: istio-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: autoscaling
        hookPhase: Running
        kind: HorizontalPodAutoscaler
        message: horizontalpodautoscaler.autoscaling/istiod unchanged
        name: istiod
        namespace: istio-system
        status: Synced
        syncPhase: Sync
        version: v2
      - group: admissionregistration.k8s.io
        hookPhase: Running
        kind: MutatingWebhookConfiguration
        message: mutatingwebhookconfiguration.admissionregistration.k8s.io/istio-sidecar-injector
          configured
        name: istio-sidecar-injector
        namespace: istio-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: admissionregistration.k8s.io
        hookPhase: Running
        kind: ValidatingWebhookConfiguration
        message: validatingwebhookconfiguration.admissionregistration.k8s.io/istio-validator-istio-system
          configured
        name: istio-validator-istio-system
        namespace: istio-system
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 1.23.2
      source:
        chart: istiod
        helm:
          valueFiles:
          - values.yaml
          values: |-
            defaults:
              meshConfig:
                accessLogFile: "/dev/stdout"
                # Set accessLogEncoding to JSON or TEXT to configure sidecar access log
                accessLogEncoding: 'TEXT'
              pilot:
                resources:
                  requests:
                    cpu: 300m
                    memory: 300Mi
            global:
              proxy:
                init:
                  resources:
                    requests:
                      cpu: 10m
                      memory: 128Mi
                    limits:
                      cpu: 2000m
                      memory: 1024Mi
        repoURL: https://istio-release.storage.googleapis.com/charts
        targetRevision: 1.23.2
  reconciledAt: "2024-11-12T14:06:07Z"
  resources:
  - kind: ConfigMap
    name: istio
    namespace: istio-system
    status: Synced
    version: v1
  - kind: ConfigMap
    name: istio-sidecar-injector
    namespace: istio-system
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: Service
    name: istiod
    namespace: istio-system
    status: Synced
    version: v1
  - kind: ServiceAccount
    name: istiod
    namespace: istio-system
    status: Synced
    version: v1
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: istio-sidecar-injector
    status: Synced
    version: v1
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: istio-validator-istio-system
    status: OutOfSync
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: istiod
    namespace: istio-system
    status: Synced
    version: v1
  - group: autoscaling
    health:
      message: recommended size matches current size
      status: Healthy
    kind: HorizontalPodAutoscaler
    name: istiod
    namespace: istio-system
    status: Synced
    version: v2
  - group: policy
    kind: PodDisruptionBudget
    name: istiod
    namespace: istio-system
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: istio-reader-clusterrole-istio-system
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: istiod-clusterrole-istio-system
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: istiod-gateway-controller-istio-system
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: istio-reader-clusterrole-istio-system
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: istiod-clusterrole-istio-system
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: istiod-gateway-controller-istio-system
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: Role
    name: istiod
    namespace: istio-system
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: istiod
    namespace: istio-system
    status: Synced
    version: v1
  sourceType: Helm
  summary:
    images:
    - docker.io/istio/pilot:1.23.2
  sync:
    comparedTo:
      destination:
        namespace: istio-system
        server: https://kubernetes.default.svc
      source:
        chart: istiod
        helm:
          valueFiles:
          - values.yaml
          values: |-
            defaults:
              meshConfig:
                accessLogFile: "/dev/stdout"
                # Set accessLogEncoding to JSON or TEXT to configure sidecar access log
                accessLogEncoding: 'TEXT'
              pilot:
                resources:
                  requests:
                    cpu: 300m
                    memory: 300Mi
            global:
              proxy:
                init:
                  resources:
                    requests:
                      cpu: 10m
                      memory: 128Mi
                    limits:
                      cpu: 2000m
                      memory: 1024Mi
        repoURL: https://istio-release.storage.googleapis.com/charts
        targetRevision: 1.23.2
    revision: 1.23.2
    status: OutOfSync
