apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2024-10-15T07:25:28Z"
  generation: 12376
  name: opentelemetry-operator
  namespace: argocd
  resourceVersion: "7359027"
  uid: e72c23d2-8ca4-4a0c-9df5-129cbd42aa06
spec:
  destination:
    namespace: tracing
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: opentelemetry-operator
    helm:
      valueFiles:
      - values.yaml
      values: |-
        manager:
          collectorImage:
            repository: otel/opentelemetry-collector-k8s
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.71.0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
  - deployStartedAt: "2024-10-15T07:51:12Z"
    deployedAt: "2024-10-15T07:51:23Z"
    id: 0
    initiatedBy:
      username: admin
    revision: 0.71.0
    source:
      chart: opentelemetry-operator
      helm:
        valueFiles:
        - values.yaml
        values: |-
          manager:
            collectorImage:
              repository: otel/opentelemetry-collector-k8s
      repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      targetRevision: 0.71.0
  operationState:
    finishedAt: "2024-10-15T07:51:24Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        revision: 0.71.0
        syncOptions:
        - CreateNamespace=true
        syncStrategy:
          hook: {}
    phase: Succeeded
    startedAt: "2024-10-15T07:51:12Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: Namespace
        message: namespace/tracing created
        name: tracing
        namespace: ""
        status: Synced
        syncPhase: PreSync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ServiceAccount
        message: serviceaccount/opentelemetry-operator created
        name: opentelemetry-operator
        namespace: tracing
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apiextensions.k8s.io
        hookPhase: Running
        kind: CustomResourceDefinition
        message: customresourcedefinition.apiextensions.k8s.io/instrumentations.opentelemetry.io
          created
        name: instrumentations.opentelemetry.io
        namespace: tracing
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apiextensions.k8s.io
        hookPhase: Running
        kind: CustomResourceDefinition
        message: customresourcedefinition.apiextensions.k8s.io/opampbridges.opentelemetry.io
          created
        name: opampbridges.opentelemetry.io
        namespace: tracing
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apiextensions.k8s.io
        hookPhase: Running
        kind: CustomResourceDefinition
        message: customresourcedefinition.apiextensions.k8s.io/opentelemetrycollectors.opentelemetry.io
          created
        name: opentelemetrycollectors.opentelemetry.io
        namespace: tracing
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: ClusterRole
        message: "clusterrole.rbac.authorization.k8s.io/opentelemetry-operator-proxy
          reconciled. reconciliation required create\n\tmissing rules added:\n\t\t{Verbs:[create]
          APIGroups:[authentication.k8s.io] Resources:[tokenreviews] ResourceNames:[]
          NonResourceURLs:[]}\n\t\t{Verbs:[create] APIGroups:[authorization.k8s.io]
          Resources:[subjectaccessreviews] ResourceNames:[] NonResourceURLs:[]}. clusterrole.rbac.authorization.k8s.io/opentelemetry-operator-proxy
          configured. Warning: resource clusterroles/opentelemetry-operator-proxy
          is missing the kubectl.kubernetes.io/last-applied-configuration annotation
          which is required by  apply.  apply should only be used on resources created
          declaratively by either  create --save-config or  apply. The missing annotation
          will be patched automatically."
        name: opentelemetry-operator-proxy
        namespace: tracing
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: ClusterRole
        message: "clusterrole.rbac.authorization.k8s.io/opentelemetry-operator-metrics
          reconciled. reconciliation required create\n\tmissing rules added:\n\t\t{Verbs:[get]
          APIGroups:[] Resources:[] ResourceNames:[] NonResourceURLs:[/metrics]}.
          clusterrole.rbac.authorization.k8s.io/opentelemetry-operator-metrics configured.
          Warning: resource clusterroles/opentelemetry-operator-metrics is missing
          the kubectl.kubernetes.io/last-applied-configuration annotation which is
          required by  apply.  apply should only be used on resources created declaratively
          by either  create --save-config or  apply. The missing annotation will be
          patched automatically."
        name: opentelemetry-operator-metrics
        namespace: tracing
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: ClusterRole
        message: "clusterrole.rbac.authorization.k8s.io/opentelemetry-operator-manager
          reconciled. reconciliation required create\n\tmissing rules added:\n\t\t{Verbs:[create
          delete get list patch update watch] APIGroups:[] Resources:[configmaps persistentvolumeclaims
          persistentvolumes pods serviceaccounts services] ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[create
          patch] APIGroups:[] Resources:[events] ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[list
          watch] APIGroups:[] Resources:[namespaces] ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[create
          delete get list patch update watch] APIGroups:[apps] Resources:[daemonsets
          deployments statefulsets] ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[get
          list watch] APIGroups:[apps extensions] Resources:[replicasets] ResourceNames:[]
          NonResourceURLs:[]}\n\t\t{Verbs:[create delete get list patch update watch]
          APIGroups:[autoscaling] Resources:[horizontalpodautoscalers] ResourceNames:[]
          NonResourceURLs:[]}\n\t\t{Verbs:[get list watch] APIGroups:[batch] Resources:[jobs]
          ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[get list watch] APIGroups:[config.openshift.io]
          Resources:[infrastructures infrastructures/status] ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[create
          get list update] APIGroups:[coordination.k8s.io] Resources:[leases] ResourceNames:[]
          NonResourceURLs:[]}\n\t\t{Verbs:[create delete get list patch update watch]
          APIGroups:[monitoring.coreos.com] Resources:[podmonitors servicemonitors]
          ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[create delete get list
          patch update watch] APIGroups:[networking.k8s.io] Resources:[ingresses]
          ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[get list patch update
          watch] APIGroups:[opentelemetry.io] Resources:[instrumentations] ResourceNames:[]
          NonResourceURLs:[]}\n\t\t{Verbs:[create delete get list patch update watch]
          APIGroups:[opentelemetry.io] Resources:[opampbridges] ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[update]
          APIGroups:[opentelemetry.io] Resources:[opampbridges/finalizers] ResourceNames:[]
          NonResourceURLs:[]}\n\t\t{Verbs:[get patch update] APIGroups:[opentelemetry.io]
          Resources:[opampbridges/status] ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[get
          list patch update watch] APIGroups:[opentelemetry.io] Resources:[opentelemetrycollectors]
          ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[get patch update] APIGroups:[opentelemetry.io]
          Resources:[opentelemetrycollectors/finalizers] ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[get
          patch update] APIGroups:[opentelemetry.io] Resources:[opentelemetrycollectors/status]
          ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[create delete get list
          patch update watch] APIGroups:[policy] Resources:[poddisruptionbudgets]
          ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[create delete get list
          patch update watch] APIGroups:[route.openshift.io] Resources:[routes routes/custom-host]
          ResourceNames:[] NonResourceURLs:[]}. clusterrole.rbac.authorization.k8s.io/opentelemetry-operator-manager
          configured. Warning: resource clusterroles/opentelemetry-operator-manager
          is missing the kubectl.kubernetes.io/last-applied-configuration annotation
          which is required by  apply.  apply should only be used on resources created
          declaratively by either  create --save-config or  apply. The missing annotation
          will be patched automatically."
        name: opentelemetry-operator-manager
        namespace: tracing
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: ClusterRoleBinding
        message: "clusterrolebinding.rbac.authorization.k8s.io/opentelemetry-operator-manager
          reconciled. reconciliation required create\n\tmissing subjects added:\n\t\t{Kind:ServiceAccount
          APIGroup: Name:opentelemetry-operator Namespace:tracing}. clusterrolebinding.rbac.authorization.k8s.io/opentelemetry-operator-manager
          configured. Warning: resource clusterrolebindings/opentelemetry-operator-manager
          is missing the kubectl.kubernetes.io/last-applied-configuration annotation
          which is required by  apply.  apply should only be used on resources created
          declaratively by either  create --save-config or  apply. The missing annotation
          will be patched automatically."
        name: opentelemetry-operator-manager
        namespace: tracing
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: ClusterRoleBinding
        message: "clusterrolebinding.rbac.authorization.k8s.io/opentelemetry-operator-proxy
          reconciled. reconciliation required create\n\tmissing subjects added:\n\t\t{Kind:ServiceAccount
          APIGroup: Name:opentelemetry-operator Namespace:tracing}. clusterrolebinding.rbac.authorization.k8s.io/opentelemetry-operator-proxy
          configured. Warning: resource clusterrolebindings/opentelemetry-operator-proxy
          is missing the kubectl.kubernetes.io/last-applied-configuration annotation
          which is required by  apply.  apply should only be used on resources created
          declaratively by either  create --save-config or  apply. The missing annotation
          will be patched automatically."
        name: opentelemetry-operator-proxy
        namespace: tracing
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: Role
        message: "role.rbac.authorization.k8s.io/opentelemetry-operator-leader-election
          reconciled. reconciliation required create\n\tmissing rules added:\n\t\t{Verbs:[get
          list watch create update patch delete] APIGroups:[] Resources:[configmaps]
          ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[get update patch] APIGroups:[]
          Resources:[configmaps/status] ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[create
          patch] APIGroups:[] Resources:[events] ResourceNames:[] NonResourceURLs:[]}.
          role.rbac.authorization.k8s.io/opentelemetry-operator-leader-election configured.
          Warning: resource roles/opentelemetry-operator-leader-election is missing
          the kubectl.kubernetes.io/last-applied-configuration annotation which is
          required by  apply.  apply should only be used on resources created declaratively
          by either  create --save-config or  apply. The missing annotation will be
          patched automatically."
        name: opentelemetry-operator-leader-election
        namespace: tracing
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: RoleBinding
        message: "rolebinding.rbac.authorization.k8s.io/opentelemetry-operator-leader-election
          reconciled. reconciliation required create\n\tmissing subjects added:\n\t\t{Kind:ServiceAccount
          APIGroup: Name:opentelemetry-operator Namespace:tracing}. rolebinding.rbac.authorization.k8s.io/opentelemetry-operator-leader-election
          configured. Warning: resource rolebindings/opentelemetry-operator-leader-election
          is missing the kubectl.kubernetes.io/last-applied-configuration annotation
          which is required by  apply.  apply should only be used on resources created
          declaratively by either  create --save-config or  apply. The missing annotation
          will be patched automatically."
        name: opentelemetry-operator-leader-election
        namespace: tracing
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/opentelemetry-operator created
        name: opentelemetry-operator
        namespace: tracing
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/opentelemetry-operator-webhook created
        name: opentelemetry-operator-webhook
        namespace: tracing
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/opentelemetry-operator created
        name: opentelemetry-operator
        namespace: tracing
        status: Synced
        syncPhase: Sync
        version: v1
      - group: admissionregistration.k8s.io
        hookPhase: Running
        kind: MutatingWebhookConfiguration
        message: mutatingwebhookconfiguration.admissionregistration.k8s.io/opentelemetry-operator-mutation
          created
        name: opentelemetry-operator-mutation
        namespace: tracing
        status: Synced
        syncPhase: Sync
        version: v1
      - group: cert-manager.io
        hookPhase: Running
        kind: Issuer
        message: issuer.cert-manager.io/opentelemetry-operator-selfsigned-issuer created
        name: opentelemetry-operator-selfsigned-issuer
        namespace: tracing
        status: Synced
        syncPhase: Sync
        version: v1
      - group: cert-manager.io
        hookPhase: Running
        kind: Certificate
        message: certificate.cert-manager.io/opentelemetry-operator-serving-cert created
        name: opentelemetry-operator-serving-cert
        namespace: tracing
        status: Synced
        syncPhase: Sync
        version: v1
      - group: admissionregistration.k8s.io
        hookPhase: Running
        kind: ValidatingWebhookConfiguration
        message: validatingwebhookconfiguration.admissionregistration.k8s.io/opentelemetry-operator-validation
          created
        name: opentelemetry-operator-validation
        namespace: tracing
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 0.71.0
      source:
        chart: opentelemetry-operator
        helm:
          valueFiles:
          - values.yaml
          values: |-
            manager:
              collectorImage:
                repository: otel/opentelemetry-collector-k8s
        repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
        targetRevision: 0.71.0
  reconciledAt: "2024-11-12T14:07:12Z"
  resources:
  - health:
      status: Healthy
    kind: Service
    name: opentelemetry-operator
    namespace: tracing
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: Service
    name: opentelemetry-operator-webhook
    namespace: tracing
    status: Synced
    version: v1
  - kind: ServiceAccount
    name: opentelemetry-operator
    namespace: tracing
    status: Synced
    version: v1
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: opentelemetry-operator-mutation
    status: Synced
    version: v1
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: opentelemetry-operator-validation
    status: Synced
    version: v1
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: instrumentations.opentelemetry.io
    status: Synced
    version: v1
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: opampbridges.opentelemetry.io
    status: Synced
    version: v1
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: opentelemetrycollectors.opentelemetry.io
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: opentelemetry-operator
    namespace: tracing
    status: Synced
    version: v1
  - group: cert-manager.io
    health:
      message: Certificate is up to date and has not expired
      status: Healthy
    kind: Certificate
    name: opentelemetry-operator-serving-cert
    namespace: tracing
    status: Synced
    version: v1
  - group: cert-manager.io
    health:
      status: Healthy
    kind: Issuer
    name: opentelemetry-operator-selfsigned-issuer
    namespace: tracing
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: opentelemetry-operator-manager
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: opentelemetry-operator-metrics
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: opentelemetry-operator-proxy
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: opentelemetry-operator-manager
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: opentelemetry-operator-proxy
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: Role
    name: opentelemetry-operator-leader-election
    namespace: tracing
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: opentelemetry-operator-leader-election
    namespace: tracing
    status: Synced
    version: v1
  sourceType: Helm
  summary:
    images:
    - ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:0.110.0
    - quay.io/brancz/kube-rbac-proxy:v0.15.0
  sync:
    comparedTo:
      destination:
        namespace: tracing
        server: https://kubernetes.default.svc
      source:
        chart: opentelemetry-operator
        helm:
          valueFiles:
          - values.yaml
          values: |-
            manager:
              collectorImage:
                repository: otel/opentelemetry-collector-k8s
        repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
        targetRevision: 0.71.0
    revision: 0.71.0
    status: Synced
