apiVersion: v1
data:
  name: ZGVsaXZlcnloZXJvIA==
  project: ZGVmYXVsdA==
  type: aGVsbQ==
  url: aHR0cHM6Ly9jaGFydHMuZGVsaXZlcnloZXJvLmlvLw==
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  creationTimestamp: "2024-11-12T13:49:04Z"
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-3542215613
  namespace: argocd
  resourceVersion: "7355648"
  uid: fe495c19-829d-477a-aba2-6a001929b6fb
type: Opaque
