apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2024-10-12T15:10:56Z"
  generation: 88
  name: gateway
  namespace: argocd
  resourceVersion: "22702"
  uid: e392d9a9-2032-4899-ac51-37e7b95508f4
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gateway
    helm:
      valueFiles:
      - values.yaml
      values: |-
        defaults:
          service:
            type: LoadBalancer
            # type: NodePort
            externalTrafficPolicy: "Local"
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.23.2
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
  - deployStartedAt: "2024-10-12T15:10:58Z"
    deployedAt: "2024-10-12T15:11:06Z"
    id: 0
    initiatedBy:
      automated: true
    revision: 1.23.2
    source:
      chart: gateway
      helm:
        valueFiles:
        - values.yaml
        values: |-
          defaults:
            service:
              type: NodePort
              externalTrafficPolicy: "Local"
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.23.2
  - deployStartedAt: "2024-10-12T16:15:29Z"
    deployedAt: "2024-10-12T16:15:31Z"
    id: 1
    initiatedBy:
      username: admin
    revision: 1.23.2
    source:
      chart: gateway
      helm:
        valueFiles:
        - values.yaml
        values: |-
          defaults:
            service:
              type: NodePort
              externalTrafficPolicy: "Local"
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.23.2
  - deployStartedAt: "2024-10-12T16:15:47Z"
    deployedAt: "2024-10-12T16:15:48Z"
    id: 2
    initiatedBy:
      automated: true
    revision: 1.23.2
    source:
      chart: gateway
      helm:
        valueFiles:
        - values.yaml
        values: |-
          defaults:
            service:
              type: LoadBalancer
              externalTrafficPolicy: "Local"
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.23.2
  - deployStartedAt: "2024-10-12T16:30:53Z"
    deployedAt: "2024-10-12T16:30:54Z"
    id: 3
    initiatedBy:
      automated: true
    revision: 1.23.2
    source:
      chart: gateway
      helm:
        valueFiles:
        - values.yaml
        values: |-
          defaults:
            service:
              # type: LoadBalancer
              type: NodePort
              externalTrafficPolicy: "Local"
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.23.2
  - deployStartedAt: "2024-10-12T16:42:22Z"
    deployedAt: "2024-10-12T16:42:23Z"
    id: 4
    initiatedBy:
      automated: true
    revision: 1.23.2
    source:
      chart: gateway
      helm:
        valueFiles:
        - values.yaml
        values: |-
          defaults:
            service:
              type: LoadBalancer
              # type: NodePort
              externalTrafficPolicy: "Local"
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.23.2
  operationState:
    finishedAt: "2024-10-12T16:42:23Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        revision: 1.23.2
        syncOptions:
        - CreateNamespace=true
    phase: Succeeded
    startedAt: "2024-10-12T16:42:22Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: ServiceAccount
        message: serviceaccount/gateway unchanged
        name: gateway
        namespace: istio-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: Role
        message: role.rbac.authorization.k8s.io/gateway reconciled. role.rbac.authorization.k8s.io/gateway
          unchanged
        name: gateway
        namespace: istio-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: RoleBinding
        message: rolebinding.rbac.authorization.k8s.io/gateway reconciled. rolebinding.rbac.authorization.k8s.io/gateway
          unchanged
        name: gateway
        namespace: istio-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/gateway configured
        name: gateway
        namespace: istio-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/gateway configured
        name: gateway
        namespace: istio-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: autoscaling
        hookPhase: Running
        kind: HorizontalPodAutoscaler
        message: horizontalpodautoscaler.autoscaling/gateway unchanged
        name: gateway
        namespace: istio-system
        status: Synced
        syncPhase: Sync
        version: v2
      revision: 1.23.2
      source:
        chart: gateway
        helm:
          valueFiles:
          - values.yaml
          values: |-
            defaults:
              service:
                type: LoadBalancer
                # type: NodePort
                externalTrafficPolicy: "Local"
        repoURL: https://istio-release.storage.googleapis.com/charts
        targetRevision: 1.23.2
  reconciledAt: "2024-10-12T16:59:44Z"
  resources:
  - health:
      status: Healthy
    kind: Service
    name: gateway
    namespace: istio-system
    status: Synced
    version: v1
  - kind: ServiceAccount
    name: gateway
    namespace: istio-system
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: gateway
    namespace: istio-system
    status: Synced
    version: v1
  - group: autoscaling
    health:
      message: the HPA controller was able to get the target's current scale
      status: Healthy
    kind: HorizontalPodAutoscaler
    name: gateway
    namespace: istio-system
    status: Synced
    version: v2
  - group: rbac.authorization.k8s.io
    kind: Role
    name: gateway
    namespace: istio-system
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: gateway
    namespace: istio-system
    status: Synced
    version: v1
  sourceType: Helm
  summary:
    images:
    - docker.io/istio/proxyv2:1.23.2
  sync:
    comparedTo:
      destination:
        namespace: istio-system
        server: https://kubernetes.default.svc
      source:
        chart: gateway
        helm:
          valueFiles:
          - values.yaml
          values: |-
            defaults:
              service:
                type: LoadBalancer
                # type: NodePort
                externalTrafficPolicy: "Local"
        repoURL: https://istio-release.storage.googleapis.com/charts
        targetRevision: 1.23.2
    revision: 1.23.2
    status: Synced
