apiVersion: v1
data:
  auth: VXZvemx1NGdSdFMxQU10Tw==
kind: Secret
metadata:
  creationTimestamp: "2024-10-12T14:44:12Z"
  name: argocd-redis
  namespace: argocd
  resourceVersion: "1474"
  uid: f74f2bbc-731b-40e8-a70a-44e352925689
type: Opaque
