apiVersion: v1
data:
  name: Yml0bmFtaSA=
  project: ZGVmYXVsdA==
  type: aGVsbQ==
  url: aHR0cHM6Ly9jaGFydHMuYml0bmFtaS5jb20vYml0bmFtaQ==
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  creationTimestamp: "2024-10-12T15:37:30Z"
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-2111645630
  namespace: argocd
  resourceVersion: "9689"
  uid: 0c80a40f-60c7-4771-9b2a-cfd7609a5a3a
type: Opaque
